import "./LegalPage.css";

import { Link } from "react-router-dom";

function Terms() {
  return (
    <div className="legal-page">
      <div className="legal-card">
        <div className="legal-brand">⚽</div>

        <span className="legal-kicker">TOP ELEVEN TOOLS</span>

        <h1>Terms of Service</h1>

        <p className="legal-updated">Last updated: September 2026</p>

        <section>
          <h2>1. Acceptance of terms</h2>

          <p>
            By accessing or using Top Eleven Tools, you agree to these Terms of
            Service and to use the application in accordance with applicable
            laws.
          </p>
        </section>

        <section>
          <h2>2. Use of the service</h2>

          <p>
            Top Eleven Tools provides tools, simulations and analysis features
            for informational and entertainment purposes.
          </p>

          <p>
            Users are responsible for the information they enter and for how
            they use the results generated by the application.
          </p>
        </section>

        <section>
          <h2>3. User accounts</h2>

          <p>
            Users are responsible for maintaining the security of their account
            credentials and for activity performed through their account.
          </p>
        </section>

        <section>
          <h2>4. Availability</h2>

          <p>
            We may modify, suspend or discontinue features of the service when
            necessary for maintenance, security, development or other
            operational reasons.
          </p>
        </section>

        <section>
          <h2>5. Third-party services</h2>

          <p>
            The application may rely on third-party services for authentication,
            hosting, storage and other infrastructure.
          </p>
        </section>

        <section>
          <h2>6. Contact</h2>

          <p>
            Questions regarding these terms may be directed to the Top Eleven
            Tools team through the contact information provided by the
            application.
          </p>
        </section>

        <div className="legal-navigation">
          <Link to="/login">← BACK TO LOGIN</Link>

          <Link to="/privacy">PRIVACY</Link>

          <Link to="/data-deletion">DATA DELETION</Link>
        </div>
      </div>
    </div>
  );
}

export default Terms;
